[workspace]
members = [
    "node",
    "pallets/template",
     "pallets/crud",
     "pallets/cal",
     "pallets/xtokens",
     "pallets/date",
    #  "pallets/sender",
    "runtime",
]
[profile.release]
panic = "unwind"

# [dependencies]
# amiquip = "0.4.0"
